#- topic_name: "camera"
#  ros_type_name: "sensor_msgs/msg/Image"
#  gz_type_name: "gz.msgs.Image"

# Set just ROS topic name, applies to both
#- gz_topic_name: "camera_info"
#  ros_type_name: "sensor_msgs/msg/CameraInfo"
#  gz_type_name: "gz.msgs.CameraInfo"

# Set just GZ topic name, applies to both
- gz_topic_name: "lidar"
  ros_topic_name: "gazebo_sim/lidar"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"

# Set each topic name explicitly
- gz_topic_name: "lidar/points"
  ros_topic_name: "gazebo_sim/lidar/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"

# Set each topic name explicitly
- gz_topic_name: "/model/robot/tf"
  ros_topic_name: "gazebo_sim/robot/tf"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"

# Set each topic name explicitly
- gz_topic_name: "model/robot/odometry"
  ros_topic_name: "gazebo_sim/robot/odometry"
  ros_type_name: "nav_msgs/msg/Odometry"
  gz_type_name: "gz.msgs.Odometry"

- gz_topic_name: "imu"
  ros_topic_name: "gazebo_sim/robot/imu"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "gz.msgs.IMU"

- topic_name: "/clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  subscriber_queue: 10
  publisher_queue: 10
  lazy: false
  direction: "GZ_TO_ROS"